services:

  mysql:
    image: mysql:8
    container_name: uf_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: josefa
      MYSQL_DATABASE: ultimatefitness_db
      MYSQL_USER: jose
      MYSQL_PASSWORD: josefa
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - uf_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: uf_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.docker
    depends_on:
      - mysql
    networks:
      - uf_net

  nginx:
    image: nginx:alpine
    container_name: uf_nginx
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - uf_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uf-api.rule=Host(`api.ultimatefitnessuf.com`)"
      - "traefik.http.routers.uf-api.entrypoints=websecure"
      - "traefik.http.routers.uf-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.uf-api.loadbalancer.server.port=80"
      - "traefik.http.routers.uf-api.middlewares=cors"

      # Middleware CORS:
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworigin=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowcredentials=true"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: uf_frontend
    restart: unless-stopped
    networks:
      - uf_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uf-web.rule=Host(`ultimatefitnessuf.com`)"
      - "traefik.http.routers.uf-web.entrypoints=websecure"
      - "traefik.http.routers.uf-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.uf-web.loadbalancer.server.port=80"

volumes:
  mysql_data:

networks:
  uf_net:
    driver: bridge
