security:
    password_hashers:
        App\Entity\Usuario:
            algorithm: auto
        App\Entity\Entrenador:
            algorithm: auto

    providers:
        usuario_provider:
            entity:
                class: App\Entity\Usuario
                property: email

        entrenador_provider:
            entity:
                class: App\Entity\Entrenador
                property: email

        chain_provider:
            chain:
                providers: [usuario_provider, entrenador_provider]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_user:
            pattern: ^/api/login$
            stateless: true
            provider: usuario_provider
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: App\Security\UsuarioLoginSuccessHandler
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        login_trainer:
            pattern: ^/api/entrenador/login$
            stateless: true
            provider: entrenador_provider
            json_login:
                check_path: /api/entrenador/login
                username_path: email
                password_path: password
                success_handler: App\Security\EntrenadorLoginSuccessHandler
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            provider: chain_provider
            jwt: ~

    access_control:
        - { path: ^/api/login$, roles: PUBLIC_ACCESS }
        - { path: ^/api/entrenador/login$, roles: PUBLIC_ACCESS }
        - { path: ^/api/register$, roles: PUBLIC_ACCESS }
        - { path: ^/api/public, roles: PUBLIC_ACCESS }
        - { path: ^/api/custom/dietas/publicas, roles: PUBLIC_ACCESS }
        - { path: ^/api/custom/dietas/\d+/plan-diario, roles: PUBLIC_ACCESS }

        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
